export const NOTIFICATION_TYPES = {
  ANALYSIS_COMPLETED: 'ANALYSIS_COMPLETED',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',
  RECRUITER_ANALYSIS_COMPLETED: 'RECRUITER_ANALYSIS_COMPLETED',
  SHARE_CREATED: 'SHARE_CREATED',
  SHARE_DISABLED: 'SHARE_DISABLED',
  SYSTEM: 'SYSTEM',
};

export default NOTIFICATION_TYPES;
